### PR TITLE
Adapt the CPython 3.9+ C-API usage to use newer macros

### LINKED ISSUE #862: Fail to build with Python 3.13
## Long story short

The package cannot be built on Python 3.13.

## Expected behaviour

The package can be built successfully when running `pip install multidict`.

## Actual behaviour

> Building wheels for collected packages: multidict
  Building wheel for multidict (pyproject.toml) ... error
  error: subprocess-exited-with-error
  × Building wheel for multidict (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [116 lines of output]
      *********************
      * Accelerated build *
      *********************
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-313
      ......
      "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\luoga\Desktop\cpython\include -IC:\Users\luoga\Desktop\cpython\PC -IC:\Users\luoga\Desktop\cpython\PC "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.7.2\include\um" /Tcmultidict/_multidict.c /Fobuild\temp.win-amd64-cpython-313\Release\multidict/_multidict.obj -O2
      _multidict.c
      C:\Users\luoga\AppData\Local\Temp\pip-install-v6wr08bw\multidict_fb6642d302954696ac7c69c89da3bbd1\multidict\_multilib/istr.h(46): warning C4013: “_PyObject_CallMethodId” Undifined, Suppose returning int
      ......
      "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\bin\HostX86\x64\link.exe" /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Users\luoga\Desktop\cpython\libs /LIBPATH:C:\Users\luoga\Desktop\cpython /LIBPATH:C:\Users\luoga\Desktop\cpython\PCbuild\amd64 "/LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.7.2\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22000.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22000.0\\um\x64" /EXPORT:PyInit__multidict build\temp.win-amd64-cpython-313\Release\multidict/_multidict.obj /OUT:build\lib.win-amd64-cpython-313\multidict\_multidict.cp313-win_amd64.pyd /IMPLIB:build\temp.win-amd64-cpython-313\Release\multidict\_multidict.cp313-win_amd64.lib
        Building lib build\temp.win-amd64-cpython-313\Release\multidict\_multidict.cp313-win_amd64.lib and object build\temp.win-amd64-cpython-313\Release\multidict\_multidict.cp313-win_amd64.exp
      _multidict.obj : error LNK2001: Cannot resolve external symbol Py_TRASHCAN_SAFE_END
      _multidict.obj : error LNK2001: Cannot resolve external symbol Py_TRASHCAN_SAFE_BEGIN
      _multidict.obj : error LNK2001: Cannot resolve external symbol _PyObject_CallMethodId

## Steps to reproduce

`pip install multidict`

## Your environment

- Windows 10
- Python 3.13
- pip 23.2

### PR DESCRIPTION
**Pull request by iemelyanov**
This patch replaces the C-APIs that have been deprecated in Python 3.9 and later removed in 3.13.

## What do these changes do?

1. Fix usage Python C API for version greater than 3.9
2. Fix segfault which I catch here https://github.com/aio-libs/multidict/blob/master/multidict/_multidict.c#L783

## Are there changes in behavior for the user?

No

## Related issue number

Fixes #862

### CODE REVIEW

**Comment by hugovk** [comment]
Thanks for the PR, I've confirmed there's a segmentation fault on all three OS on the CI for Python 3.12 (https://github.com/hugovk/multidict/actions/runs/6028022143), and the commits from this PR fixes it (https://github.com/hugovk/multidict/actions/runs/6029781394).

See also https://github.com/aio-libs/multidict/pull/877#issuecomment-1699806148.

File: multidict/_multilib/pair_list.h [hunk 1]
```diff
@@ -199,30 +203,43 @@ pair_list_shrink(pair_list_t *list)
 
 
 static inline int
-_pair_list_init(pair_list_t *list, calc_identity_func calc_identity)
+_pair_list_init(pair_list_t *list, bool calc_ci_identity)
 {
+    PyObject *str_lower = PyUnicode_InternFromString("lower");
```
Comment (serhiy-storchaka) [inline multidict/_multilib/pair_list.h:208]: Rather of caching string object "lower", it may be better to cache method object `str.lower`.

File: multidict/_multilib/istr.h [hunk 2]
```diff
@@ -43,7 +43,11 @@ istr_new(PyTypeObject *type, PyObject *args, PyObject *kwds)
     if (!ret) {
         goto fail;
     }
+#if PY_MAJOR_VERSION >= 3 && PY_MINOR_VERSION >= 9
+    s = PyObject_CallMethod(ret, "lower", NULL);
```
[the remark this answers is not in the document]
Comment (iemelyanov) [reply multidict/_multilib/istr.h]: Please look last changes, I moved multidict_str_lower to global vars and use it here and in pair_list

File: multidict/_multilib/pair_list.h (hunk 1 above)
Comment (iemelyanov) [reply multidict/_multilib/pair_list.h]: `str.lower` can't work with `CallMethod`

File: multidict/_multidict.c [hunk 3]
```diff
@@ -777,9 +785,12 @@ multidict_add(MultiDictObject *self, PyObject *const *args,
         return NULL;
     }
 #else
-    static _PyArg_Parser _parser = {NULL, _keywords, "add", 0};
+    static _PyArg_Parser _parser = {
```
[the remark this answers is not in the document]
Comment (iemelyanov) [reply multidict/_multidict.c:788]: We have a test for it https://github.com/aio-libs/multidict/blob/master/tests/test_mutable_multidict.py#L333

[the remark this answers is not in the document]
Comment (serhiy-storchaka) [reply multidict/_multidict.c:788]: But why does such test exist at first place?

`_PyArg_Parser` is a deep internal tool, it is not purposed to be used outside of CPython. It is expected that the third-party code uses good old and slow `PyArg_ParseTupleAndKeywords` for parsing keyword arguments, or handle it by hand-made code.

It is out of the scope of this issue, but I would consider deprecating accepting keyword arguments in this function.

[the remark this answers is not in the document]
Comment (iemelyanov) [reply multidict/_multidict.c:788]: This can be done in another PR

**Comment by h-vetinari** [comment]
Any news on this? We're thinking about backporting this patch in conda-forge to the last released, in order to unbreak things. It's always preferable though if the respective patches are merged upstream first.

**Comment by JeanChristopheMorinPerso** [comment]
We also backported this PR in https://github.com/AnacondaRecipes/multidict-feedstock/pull/7

**Comment by stonebig** [comment]
merging pulls 828, 829, 864 reduce quite a bit the compiling complains on windows

**Comment by tacaswell** [comment]
This is still failing to build with py313 (Python 3.13.0a2+)

```
      gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O3 -Wall -DCYTHON_FAST_THREAD_STATE=0 -fPIC -I/home/tcaswell/.virtualenvs/cp_main/include -I/home/tcaswell/.pybuild/cp_main/include/python3.13 -c multidict/_multidict.c -o build/temp.linux-x86_64-cpython-313/multidict/_multidict.o -O2 -std=c99 -Wall -Wsign-compare -Wconversion -fno-strict-aliasing -pedantic
      In file included from /home/tcaswell/.pybuild/cp_main/include/python3.13/Python.h:121,
                       from multidict/_multidict.c:1:
      /home/tcaswell/.pybuild/cp_main/include/python3.13/cpython/optimizer.h:53:3: warning: redefinition of typedef ‘_PyOptimizerObject’ [-Wpedantic]
         53 | } _PyOptimizerObject;
            |   ^~~~~~~~~~~~~~~~~~
      /home/tcaswell/.pybuild/cp_main/include/python3.13/cpython/optimizer.h:40:35: note: previous declaration of ‘_PyOptimizerObject’ with type ‘_PyOptimizerObject’
         40 | typedef struct _PyOptimizerObject _PyOptimizerObject;
            |                                   ^~~~~~~~~~~~~~~~~~
      multidict/_multidict.c: In function ‘multidict_getall’:
      multidict/_multidict.c:452:12: error: unknown type name ‘_PyArg_Parser’
        452 |     static _PyArg_Parser _parser = {"O|O:getall", _keywords, 0};
            |            ^~~~~~~~~~~~~
      multidict/_multidict.c:452:37: warning: initialization of ‘int’ from ‘char *’ makes integer from pointer without a cast [-Wint-conversion]
        452 |     static _PyArg_Parser _parser = {"O|O:getall", _keywords, 0};
            |                                     ^~~~~~~~~~~~
      multidict/_multidict.c:452:37: note: (near initialization for ‘_parser’)
      multidict/_multidict.c:452:37: error: initializer element is not computable at load time
      multidict/_multidict.c:452:37: note: (near initialization for ‘_parser’)
      multidict/_multidict.c:452:51: warning: excess elements in scalar initializer
        452 |     static _PyArg_Parser _parser = {"O|O:getall", _keywords, 0};
            |                                                   ^~~~~~~~~
      multidict/_multidict.c:452:51: note: (near initialization for ‘_parser’)
      multidict/_multidict.c:452:62: warning: excess elements in scalar initializer
        452 |     static _PyArg_Parser _parser = {"O|O:getall", _keywords, 0};
            |                                                              ^
      multidict/_multidict.c:452:62: note: (near initialization for ‘_parser’)
      multidict/_multidict.c:453:10: warning: implicit declaration of function ‘_PyArg_ParseStackAndKeywords’; did you mean ‘PyArg_ParseTupleAndKeywords’? [-Wimplicit-function-declaration]
        453 |     if (!_PyArg_ParseStackAndKeywords(args, nargs, kwnames, &_parser,
            |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
            |          PyArg_ParseTupleAndKeywords
      multidict/_multidict.c: In function ‘multidict_getone’:
      multidict/_multidict.c:497:12: error: unknown type name ‘_PyArg_Parser’
        497 |     static _PyArg_Parser _parser = {"O|O:getone", _keywords, 0};
            |            ^~~~~~~~~~~~~
      multidict/_multidict.c:497:37: warning: initialization of ‘int’ from ‘char *’ makes integer from pointer without a cast [-Wint-conversion]
        497 |     static _PyArg_Parser _parser = {"O|O:getone", _keywords, 0};
            |                                     ^~~~~~~~~~~~
      multidict/_multidict.c:497:37: note: (near initialization for ‘_parser’)
      multidict/_multidict.c:497:37: error: initializer element is not computable at load time
      multidict/_multidict.c:497:37: note: (near initialization for ‘_parser’)
      multidict/_multidict.c:497:51: warning: excess elements in scalar initializer
        497 |     static _PyArg_Parser _parser = {"O|O:getone", _keywords, 0};
            |                                                   ^~~~~~~~~
      multidict/_multidict.c:497:51: note: (near initialization for ‘_parser’)
      multidict/_multidict.c:497:62: warning: excess elements in scalar initializer
        497 |     static _PyArg_Parser _parser = {"O|O:getone", _keywords, 0};
            |                                                              ^
      multidict/_multidict.c:497:62: note: (near initialization for ‘_parser’)
      multidict/_multidict.c: In function ‘multidict_get’:
      multidict/_multidict.c:532:12: error: unknown type name ‘_PyArg_Parser’
        532 |     static _PyArg_Parser _parser = {"O|O:get", _keywords, 0};
            |            ^~~~~~~~~~~~~
      multidict/_multidict.c:532:37: warning: initialization of ‘int’ from ‘char *’ makes integer from pointer without a cast [-Wint-conversion]
        532 |     static _PyArg_Parser _parser = {"O|O:get", _keywords, 0};
            |                                     ^~~~~~~~~
      multidict/_multidict.c:532:37: note: (near initialization for ‘_parser’)
      multidict/_multidict.c:532:37: error: initializer element is not computable at load time
      multidict/_multidict.c:532:37: note: (near initialization for ‘_parser’)
      multidict/_multidict.c:532:48: warning: excess elements in scalar initializer
        532 |     static _PyArg_Parser _parser = {"O|O:get", _keywords, 0};
            |                                                ^~~~~~~~~
      multidict/_multidict.c:532:48: note: (near initialization for ‘_parser’)
      multidict/_multidict.c:532:59: warning: excess elements in scalar initializer
        532 |     static _PyArg_Parser _parser = {"O|O:get", _keywords, 0};
            |                                                           ^
      multidict/_multidict.c:532:59: note: (near initialization for ‘_parser’)
      multidict/_multidict.c: In function ‘multidict_add’:
      multidict/_multidict.c:782:12: error: unknown type name ‘_PyArg_Parser’
        782 |     static _PyArg_Parser _parser = {"OO:add", _keywords, 0};
            |            ^~~~~~~~~~~~~
      multidict/_multidict.c:782:37: warning: initialization of ‘int’ from ‘char *’ makes integer from pointer without a cast [-Wint-conversion]
        782 |     static _PyArg_Parser _parser = {"OO:add", _keywords, 0};
            |                                     ^~~~~~~~
      multidict/_multidict.c:782:37: note: (near initialization for ‘_parser’)
      multidict/_multidict.c:782:37: error: initializer element is not computable at load time
      multidict/_multidict.c:782:37: note: (near initialization for ‘_parser’)
      multidict/_multidict.c:782:47: warning: excess elements in scalar initializer
        782 |     static _PyArg_Parser _parser = {"OO:add", _keywords, 0};
            |                                               ^~~~~~~~~
      multidict/_multidict.c:782:47: note: (near initialization for ‘_parser’)
      multidict/_multidict.c:782:58: warning: excess elements in scalar initializer
        782 |     static _PyArg_Parser _parser = {"OO:add", _keywords, 0};
            |                                                          ^
      multidict/_multidict.c:782:58: note: (near initialization for ‘_parser’)
      multidict/_multidict.c: In function ‘multidict_setdefault’:
      multidict/_multidict.c:844:12: error: unknown type name ‘_PyArg_Parser’
        844 |     static _PyArg_Parser _parser = {"O|O:setdefault", _keywords, 0};
            |            ^~~~~~~~~~~~~
      multidict/_multidict.c:844:37: warning: initialization of ‘int’ from ‘char *’ makes integer from pointer without a cast [-Wint-conversion]
        844 |     static _PyArg_Parser _parser = {"O|O:setdefault", _keywords, 0};
            |                                     ^~~~~~~~~~~~~~~~
      multidict/_multidict.c:844:37: note: (near initialization for ‘_parser’)
      multidict/_multidict.c:844:37: error: initializer element is not computable at load time
      multidict/_multidict.c:844:37: note: (near initialization for ‘_parser’)
      multidict/_multidict.c:844:55: warning: excess elements in scalar initializer
        844 |     static _PyArg_Parser _parser = {"O|O:setdefault", _keywords, 0};
            |                                                       ^~~~~~~~~
      multidict/_multidict.c:844:55: note: (near initialization for ‘_parser’)
      multidict/_multidict.c:844:66: warning: excess elements in scalar initializer
        844 |     static _PyArg_Parser _parser = {"O|O:setdefault", _keywords, 0};
            |                                                                  ^
      multidict/_multidict.c:844:66: note: (near initialization for ‘_parser’)
      multidict/_multidict.c: In function ‘multidict_popone’:
      multidict/_multidict.c:880:12: error: unknown type name ‘_PyArg_Parser’
        880 |     static _PyArg_Parser _parser = {"O|O:popone", _keywords, 0};
            |            ^~~~~~~~~~~~~
      multidict/_multidict.c:880:37: warning: initialization of ‘int’ from ‘char *’ makes integer from pointer without a cast [-Wint-conversion]
        880 |     static _PyArg_Parser _parser = {"O|O:popone", _keywords, 0};
            |                                     ^~~~~~~~~~~~
      multidict/_multidict.c:880:37: note: (near initialization for ‘_parser’)
      multidict/_multidict.c:880:37: error: initializer element is not computable at load time
      multidict/_multidict.c:880:37: note: (near initialization for ‘_parser’)
      multidict/_multidict.c:880:51: warning: excess elements in scalar initializer
        880 |     static _PyArg_Parser _parser = {"O|O:popone", _keywords, 0};
            |                                                   ^~~~~~~~~
      multidict/_multidict.c:880:51: note: (near initialization for ‘_parser’)
      multidict/_multidict.c:880:62: warning: excess elements in scalar initializer
        880 |     static _PyArg_Parser _parser = {"O|O:popone", _keywords, 0};
            |                                                              ^
      multidict/_multidict.c:880:62: note: (near initialization for ‘_parser’)
      multidict/_multidict.c: In function ‘multidict_pop’:
      multidict/_multidict.c:927:12: error: unknown type name ‘_PyArg_Parser’
        927 |     static _PyArg_Parser _parser = {"O|O:pop", _keywords, 0};
            |            ^~~~~~~~~~~~~
      multidict/_multidict.c:927:37: warning: initialization of ‘int’ from ‘char *’ makes integer from pointer without a cast [-Wint-conversion]
        927 |     static _PyArg_Parser _parser = {"O|O:pop", _keywords, 0};
            |                                     ^~~~~~~~~
      multidict/_multidict.c:927:37: note: (near initialization for ‘_parser’)
      multidict/_multidict.c:927:37: error: initializer element is not computable at load time
      multidict/_multidict.c:927:37: note: (near initialization for ‘_parser’)
      multidict/_multidict.c:927:48: warning: excess elements in scalar initializer
        927 |     static _PyArg_Parser _parser = {"O|O:pop", _keywords, 0};
            |                                                ^~~~~~~~~
      multidict/_multidict.c:927:48: note: (near initialization for ‘_parser’)
      multidict/_multidict.c:927:59: warning: excess elements in scalar initializer
        927 |     static _PyArg_Parser _parser = {"O|O:pop", _keywords, 0};
            |                                                           ^
      multidict/_multidict.c:927:59: note: (near initialization for ‘_parser’)
      multidict/_multidict.c: In function ‘multidict_popall’:
      multidict/_multidict.c:975:12: error: unknown type name ‘_PyArg_Parser’
        975 |     static _PyArg_Parser _parser = {"O|O:popall", _keywords, 0};
            |            ^~~~~~~~~~~~~
      multidict/_multidict.c:975:37: warning: initialization of ‘int’ from ‘char *’ makes integer from pointer without a cast [-Wint-conversion]
        975 |     static _PyArg_Parser _parser = {"O|O:popall", _keywords, 0};
            |                                     ^~~~~~~~~~~~
      multidict/_multidict.c:975:37: note: (near initialization for ‘_parser’)
      multidict/_multidict.c:975:37: error: initializer element is not computable at load time
      multidict/_multidict.c:975:37: note: (near initialization for ‘_parser’)
      multidict/_multidict.c:975:51: warning: excess elements in scalar initializer
        975 |     static _PyArg_Parser _parser = {"O|O:popall", _keywords, 0};
            |                                                   ^~~~~~~~~
      multidict/_multidict.c:975:51: note: (near initialization for ‘_parser’)
      multidict/_multidict.c:975:62: warning: excess elements in scalar initializer
        975 |     static _PyArg_Parser _parser = {"O|O:popall", _keywords, 0};
            |                                                              ^
      multidict/_multidict.c:975:62: note: (near initialization for ‘_parser’)
      error: command '/lib/ccache/bin/gcc' failed with exit code 1
      [end of output]
```

File: multidict/_multidict.c [hunk 4]
```diff
@@ -709,13 +709,21 @@ static inline void
 multidict_tp_dealloc(MultiDictObject *self)
 {
     PyObject_GC_UnTrack(self);
+#if PY_MAJOR_VERSION >= 3 && PY_MINOR_VERSION >= 9
+    Py_TRASHCAN_BEGIN(self, multidict_tp_dealloc)
```
Comment (webknjaz) [inline multidict/_multidict.c:713]: I'm not very familiar with these helpers, but shouldn't the C instructions be delimited with a semicolon?
```suggestion
    Py_TRASHCAN_BEGIN(self, multidict_tp_dealloc);
```

File: multidict/_multidict.c [hunk 5]
```diff
@@ -709,13 +709,21 @@ static inline void
...
+#else
     Py_TRASHCAN_SAFE_BEGIN(self);
+#endif
     if (self->weaklist != NULL) {
         PyObject_ClearWeakRefs((PyObject *)self);
     };
     pair_list_dealloc(&self->pairs);
     Py_TYPE(self)->tp_free((PyObject *)self);
+#if PY_MAJOR_VERSION >= 3 && PY_MINOR_VERSION >= 9
+    Py_TRASHCAN_END // there should be no code after this
```
Comment (webknjaz) [inline multidict/_multidict.c:723]: And here?
```suggestion
    Py_TRASHCAN_END;  // there should be no code after this
```

Comment (webknjaz) [reply multidict/_multidict.c:723]: Ah, nevermind. Found the macro definition and it has a semicolon:
https://github.com/python/cpython/blob/b5dc0f83adda0bde1b176c3a84cc31cd94254e73/Include/cpython/object.h#L474-L478

File: multidict/_multidict.c (hunk 4 above)
Comment (webknjaz) [reply multidict/_multidict.c:713]: This one doesn't end a semicolon, but is an loop opening:
https://github.com/python/cpython/blob/b5dc0f83adda0bde1b176c3a84cc31cd94254e73/Include/cpython/object.h#L480-L482
https://github.com/python/cpython/blob/b5dc0f83adda0bde1b176c3a84cc31cd94254e73/Include/cpython/object.h#L462-L473

So I guess we're good here... I'll mark this thread as resolved.
